import type { NewLanguage } from '../locales';

/** 최종 번역표 반영 전 사용하는 큐레이션 본문 초벌 번역. */
export const CURATION_BODY_DRAFTS: Record<string, Record<NewLanguage, string>> = {
  'korean-table': {
    'zh-CN': `韩国餐桌可以用“摆满一桌”来概括。米饭和汤放在中心，周围摆着泡菜和各种小菜。与一道主菜接一道主菜的西式餐序不同，韩国人通常从一开始就把菜一起摆上桌，在不同味道之间自由搭配。\n\n这种餐桌背后有一种叫“情”的温暖：不愿让客人空着肚子离开。因此，小菜通常免费，吃完后也可以请店员再加。热汤、新煮的米饭、咸香的小菜和酸爽的泡菜在一口中相遇，这就是韩国饮食的节奏。\n\n如果你第一次看到满桌的小碟，不必慌张。它们并不是要求你全部吃完，而更像一句“请按自己的喜好尽情品尝”的欢迎。`,
    ja: `韓国の食卓は「ハンサンチャリム」、つまり一つの膳に料理をいっぱい並べる形で表せます。ご飯と汁物を中心に、キムチやさまざまなおかずが囲みます。一皿ずつ進むコース料理とは違い、最初から並んだ料理を自由に行き来しながら味わいます。\n\nその背景には、人を温かく迎える「情（チョン）」があります。客を空腹のまま帰したくないという気持ちから、おかずは無料で、なくなればおかわりを頼めることが多いのです。熱い汁物、炊きたてのご飯、塩気のあるおかず、酸味のあるキムチが一口の中で調和します。\n\n初めて小皿の多さに驚いても、全部食べなければならないわけではありません。「好きなものを自由に楽しんでください」という韓国式の歓迎だと思ってください。`,
    'zh-TW': `韓國餐桌可以用「擺滿一桌」來概括。白飯和湯放在中央，周圍擺著泡菜與各種小菜。不同於一道主菜接一道主菜的西式餐序，韓國人通常從一開始就把餐點一起上桌，在不同味道之間自由搭配。\n\n這樣的餐桌背後有一種稱為「情」的溫暖：不願讓客人空著肚子離開。因此，小菜通常免費，吃完後也可以請店員再補。熱湯、新煮的白飯、鹹香的小菜與酸爽的泡菜在一口中相遇，形成韓式用餐的節奏。\n\n第一次看到滿桌小碟時不用緊張。它們不是要求你全部吃完，而更像一句「請依自己的喜好盡情品嚐」的歡迎。`,
    es: `Una comida coreana suele presentarse como una mesa completa: arroz y sopa en el centro, rodeados de kimchi y pequeños acompañamientos. A diferencia de un menú servido plato por plato, todo llega casi al mismo tiempo para que combines sabores libremente.\n\nDetrás de esta forma de comer está el jeong, una calidez que busca que ningún invitado se marche con hambre. Por eso los banchan suelen ser gratuitos y normalmente puedes pedir que los repongan. La sopa caliente, el arroz recién hecho, los acompañamientos salados y el kimchi ácido están pensados para encontrarse en un mismo bocado.\n\nSi es tu primera vez, no te preocupes por la cantidad de platos pequeños. No significan que debas terminarlos todos, sino que puedes elegir y disfrutar a tu ritmo.`,
  },
  fermentation: {
    'zh-CN': `韩国料理的浓郁风味背后，几乎总有发酵。白菜用盐和调味料腌制后成为泡菜，大豆发酵成熟后成为大酱和酱油，再加入辣椒便会变成甜辣的辣椒酱。\n\n过去的韩国家庭院子里常有摆放陶缸的“酱缸台”。人们相信阳光、风和时间会决定酱的味道，所以制酱曾是一年中的重要活动。发酵不仅是保存食物的方法，也会在时间中创造出鲜味、酸味和甜味。\n\n因此，陈年泡菜和长时间熟成的大酱格外珍贵。相同的食材会因温度和成熟时间而产生完全不同的味道，这正是韩国发酵饮食的魅力。`,
    ja: `韓国料理の深い味の裏には、ほとんどいつも発酵があります。白菜を塩と薬味で漬ければキムチに、大豆を発酵させればテンジャンや醤油に、唐辛子を加えれば甘辛いコチュジャンになります。\n\n昔の韓国の家には、庭に甕を並べた「チャントクテ」がありました。日差し、風、時間が味を左右すると考えられ、醤を仕込むことは一年の大切な行事でした。発酵は保存だけでなく、うま味や酸味、甘味をゆっくり生み出します。\n\nそのため、熟成したキムチや長く寝かせたテンジャンは特に大切にされます。同じ材料でも時間と温度で全く違う味になることが、韓国の発酵文化の面白さです。`,
    'zh-TW': `韓國料理的濃郁風味背後，幾乎總有發酵。白菜用鹽和調味料醃製後成為泡菜，大豆發酵熟成後成為大醬與醬油，再加入辣椒便成了甜辣的辣椒醬。\n\n過去的韓國家庭院子裡常有擺放陶甕的「醬缸臺」。人們相信陽光、風與時間會決定醬的味道，因此製醬曾是一年中的重要活動。發酵不只是保存食物的方法，也會隨時間創造出鮮味、酸味與甜味。\n\n所以，陳年泡菜和長時間熟成的大醬格外珍貴。相同食材會因溫度與熟成時間產生完全不同的味道，這正是韓國發酵飲食的魅力。`,
    es: `Detrás de los sabores intensos de la cocina coreana casi siempre hay fermentación. La col con sal y condimentos se convierte en kimchi; la soja fermentada, en doenjang y salsa de soja; y con chile nace el gochujang dulce y picante.\n\nEn los patios tradicionales había jangdokdae, filas de tinajas de barro. Se creía que el sol, el viento y el tiempo decidían el sabor, por lo que preparar las salsas era un acontecimiento anual. Fermentar no solo conserva: crea lentamente umami, acidez y dulzor.\n\nPor eso se valoran tanto el kimchi envejecido y el doenjang madurado durante años. Con los mismos ingredientes, el tiempo y la temperatura pueden producir sabores completamente distintos.`,
  },
  chimaek: {
    'zh-CN': `“치맥”由炸鸡和韩语啤酒“맥주”组合而成，指酥脆炸鸡配冰凉啤酒的韩国夜宵文化。它不只是一份菜单，也象征下班后的奖励和与朋友共度的夜晚。\n\n韩国炸鸡的魅力在于格外酥脆的外皮。炸两次后，可以裹上甜辣酱成为调味炸鸡，也可以保持原味；各点一半是很常见的选择。\n\n无论在炸鸡店、酒馆还是汉江边，치맥都很受欢迎。2002年世界杯和韩剧又让这种搭配走向世界。在韩国，“炸鸡配啤酒”几乎已经是一条公认的美食公式。`,
    ja: `「チメク」はチキンと韓国語でビールを表す「メクチュ」を合わせた言葉です。カリッと揚げたチキンと冷たいビールを楽しむ韓国の夜食文化で、仕事終わりのご褒美や友人との夜を象徴します。\n\n韓国チキンの魅力は、とても軽くて歯ざわりのよい衣です。二度揚げしたチキンに甘辛いソースを絡めればヤンニョム、何もかけなければフライド。両方を半分ずつ注文するのも定番です。\n\nチメクは店だけでなく、漢江の河川敷でも楽しまれます。2002年のワールドカップや韓国ドラマをきっかけに世界へ広がり、韓国では「チキンにはビール」が王道の組み合わせになりました。`,
    'zh-TW': `「치맥」由炸雞與韓語啤酒「맥주」組合而成，指酥脆炸雞配冰涼啤酒的韓國宵夜文化。它不只是一份餐點，也象徵下班後的獎勵，以及與朋友共度的夜晚。\n\n韓國炸雞的魅力在於格外酥脆的外皮。炸兩次後，可以裹上甜辣醬成為調味炸雞，也可以保留原味；兩種口味各點一半是很常見的選擇。\n\n無論在炸雞店、酒館或漢江邊，치맥都很受歡迎。2002年世界盃與韓劇又讓這種搭配走向世界。在韓國，「炸雞配啤酒」幾乎已是一條公認的美食公式。`,
    es: `Chimaek une chicken con maekju, “cerveza” en coreano. Es la costumbre de acompañar pollo frito crujiente con una cerveza muy fría, símbolo de una recompensa después del trabajo o de una noche con amigos.\n\nEl encanto del pollo coreano está en su cobertura extremadamente crujiente. Se fríe dos veces y puede servirse tal cual o cubierto con una salsa dulce y picante llamada yangnyeom. Pedir mitad de cada estilo es una opción muy habitual.\n\nEl chimaek se disfruta en restaurantes, bares e incluso junto al río Han. El Mundial de 2002 y los dramas coreanos ayudaron a popularizarlo en todo el mundo.`,
  },
  bunsik: {
    'zh-CN': `“분식”原本指面粉食品，如今泛指炒年糕、紫菜包饭、韩式血肠和炸物等便宜又快捷的街头小吃。许多韩国人都对校门口的小吃店有自己的回忆。\n\n最具代表性的当然是炒年糕。软糯年糕在甜辣的辣椒酱中煮得浓稠，配上鱼糕汤后辣味会更柔和。小吃的另一魅力是自由搭配：紫菜包饭蘸炒年糕酱、炸物泡进酱汁，再配上一份韩式血肠。\n\n它不昂贵，也不华丽，却是最贴近日常韩国生活的味道。一盘炒年糕里装着的不只是辣味，还有街巷与青春的记忆。`,
    ja: `「プンシク」はもともと小麦粉を使った料理を指しましたが、今ではトッポッキ、キンパ、スンデ、揚げ物など、手軽で安い屋台料理の総称です。多くの韓国人にとって、学校前のプンシク店は思い出の場所です。\n\n代表はもちろんトッポッキ。もちもちした餅を甘辛いコチュジャンだれで煮込みます。おでんの汁と一緒に食べると辛さがやわらぎます。キンパや揚げ物をたれにつけ、スンデを添えるなど、自由に組み合わせるのも楽しみです。\n\n高価でも華やかでもありませんが、プンシクは韓国の日常に最も近い味です。一皿のトッポッキには、路地や青春の記憶まで詰まっています。`,
    'zh-TW': `「분식」原本指麵粉食品，如今泛指辣炒年糕、紫菜飯捲、韓式血腸與炸物等平價又快速的街頭小吃。許多韓國人都對校門口的小吃店有自己的回憶。\n\n最具代表性的當然是辣炒年糕。Q彈年糕在甜辣的辣椒醬中煮得濃稠，搭配魚板湯後辣味會更柔和。小吃的另一個魅力是自由搭配：紫菜飯捲蘸辣炒年糕醬、炸物泡進醬汁，再配上一份韓式血腸。\n\n它不昂貴，也不華麗，卻是最貼近日常韓國生活的味道。一盤辣炒年糕裡裝著的不只是辣味，還有街巷與青春的記憶。`,
    es: `Bunsik significaba originalmente comida hecha con harina, pero hoy reúne aperitivos callejeros baratos y rápidos como tteokbokki, gimbap, sundae y frituras. Muchos coreanos guardan algún recuerdo del pequeño local de bunsik frente a su escuela.\n\nLa estrella es el tteokbokki: cilindros de arroz cocidos en una salsa de gochujang dulce, picante y espesa. El caldo de pastel de pescado ayuda a suavizar el picante. También puedes mojar gimbap y frituras en la salsa o añadir sundae; no existe un orden fijo.\n\nNo es una comida cara ni elegante, pero quizá sea el sabor más cercano a la vida cotidiana de Corea y a los recuerdos de juventud.`,
  },
  'banchan-free': {
    'zh-CN': `在韩国餐厅点餐后，泡菜、拌菜等一排小碟常常会自然地摆上桌。这些“반찬”大多免费，吃完后通常也可以请店员续加。对游客来说可能很新奇，对韩国人却是日常。\n\n这种习惯源自不愿让客人空着肚子离开的“情”。丰盛地招待客人就是欢迎，因此形成了不吝惜小菜的文化。小菜的种类有时也是餐厅的自豪，会随季节更换。\n\n如果小菜吃完了，不用犹豫。说一句“可以续加小菜吗？”就足够了。不过，不同餐厅的续加政策可能不同，先礼貌询问会更安心。`,
    ja: `韓国の食堂で料理を頼むと、キムチやナムルなどの小皿が自然に並びます。これらの「パンチャン」は多くの場合無料で、なくなればおかわりをお願いできます。旅行者には不思議でも、韓国では日常的な光景です。\n\n背景には、客を空腹で帰したくないという「情」があります。たっぷりの料理でもてなすことが歓迎の表現となり、おかずを惜しまない文化が生まれました。種類の多さを店の誇りにしているところもあります。\n\n小皿が空になったら「おかわりできますか？」と丁寧に聞いてみましょう。店によってルールが異なる場合もあるため、まず確認すると安心です。`,
    'zh-TW': `在韓國餐廳點餐後，泡菜、拌菜等一排小碟常會自然地擺上桌。這些「반찬」大多免費，吃完後通常也可以請店員續加。對旅客而言或許很新奇，對韓國人卻是日常。\n\n這種習慣源自不願讓客人空著肚子離開的「情」。豐盛地招待客人就是一種歡迎，因此形成了不吝惜小菜的文化。小菜的種類有時也是餐廳的驕傲，並會隨季節更換。\n\n如果小菜吃完了，不必猶豫。禮貌問一句「可以再加小菜嗎？」就可以了。不過每家餐廳的規則可能不同，先確認會更安心。`,
    es: `Al pedir en un restaurante coreano suelen aparecer pequeños platos de kimchi, verduras sazonadas y otros acompañamientos. Estos banchan normalmente son gratuitos y a menudo se pueden reponer. Para un visitante resulta sorprendente; en Corea forma parte de la comida cotidiana.\n\nLa costumbre nace del jeong: el deseo de recibir al invitado con generosidad y no dejarlo marchar con hambre. La variedad de acompañamientos también puede ser motivo de orgullo para un restaurante y cambia según la estación.\n\nSi se termina un plato, pregunta con educación si pueden reponerlo. Las normas varían de un establecimiento a otro, por lo que siempre conviene confirmarlo.`,
  },
  'grill-cut': {
    'zh-CN': `在五花肉或排骨店，店员常会在桌上的烤盘帮忙烤肉，再用剪刀剪成适合入口的大小。第一次见到可能有些意外，但这是为了掌握火候，也让客人可以专心聊天和享用。\n\n烤肉通常不会单独吃。经典方法是把一块肉、包饭酱、大蒜和葱丝放在生菜或苏子叶上，包成一口大小的“쌈”。各种味道和口感会在一口中相遇。\n\n烤盘的滋滋声、烤出的香气，以及大家一起伸手包肉的场景，让韩国烤肉不只是一顿饭，更像一个愉快的共同仪式。`,
    ja: `サムギョプサルやカルビの店では、店員がテーブルの鉄板で肉を焼き、はさみで食べやすい大きさに切ってくれることがあります。初めは驚くかもしれませんが、焼き加減を整え、客が会話と食事を楽しめるようにするためです。\n\n焼いた肉はそのまま食べるだけではありません。レタスやえごまの葉に肉、サムジャン、にんにく、ねぎをのせ、一口で包む「サム」が定番です。一口の中でさまざまな味と食感が重なります。\n\n鉄板の音と香り、みんなで肉を焼いて包む風景まで含めて、韓国式焼肉は食事であると同時に楽しい共同体験です。`,
    'zh-TW': `在五花肉或排骨店，店員常會在桌上的烤盤幫忙烤肉，再用剪刀剪成方便入口的大小。第一次看到可能有些意外，但這是為了掌握火候，也讓客人能專心聊天與享用。\n\n烤肉通常不會單獨吃。經典方式是把一塊肉、包飯醬、大蒜與蔥絲放在生菜或紫蘇葉上，包成一口大小的「쌈」。各種味道與口感會在一口中相遇。\n\n烤盤的滋滋聲、烤出的香氣，以及大家一起動手包肉的景象，讓韓式烤肉不只是一頓飯，更像一個愉快的共同儀式。`,
    es: `En los restaurantes de samgyeopsal o galbi, el personal puede asar la carne en la plancha de la mesa y cortarla con tijeras. Aunque sorprende al principio, permite controlar el punto de cocción y que los clientes se concentren en conversar y comer.\n\nLa carne rara vez se toma sola. Lo clásico es preparar un ssam: carne, ssamjang, ajo y cebolleta sobre una hoja de lechuga o perilla, todo doblado para comerlo de un bocado.\n\nEl sonido de la plancha, el aroma y el gesto de cocinar y envolver juntos convierten la barbacoa coreana en una comida y, al mismo tiempo, en una experiencia compartida.`,
  },
  'kimchi-200': {
    'zh-CN': `很多人以为泡菜就是红色的白菜泡菜，其实它的世界更广。萝卜块泡菜、整根小萝卜泡菜、夹馅黄瓜泡菜，以及不放辣椒粉的白泡菜，种类多达数百种。\n\n泡菜的味道会随着地区和季节变化。寒冷北方的口味较清爽，炎热南方则常做得更咸更辣，方便长时间保存。春天的嫩菜、夏天的小萝卜、秋天的白菜，当季食材都能成为泡菜。\n\n关键还在制作者的“手味”。即使配方相同，不同家庭做出的味道也不同。深秋全家一起大量制作泡菜的“김장”文化，也被列入联合国教科文组织非物质文化遗产。`,
    ja: `キムチというと赤い白菜キムチを思い浮かべがちですが、世界はもっと広いものです。角切り大根のカクトゥギ、若い大根のチョンガクキムチ、きゅうりに具を詰めたオイソバギ、唐辛子を使わない白キムチなど、数百種類があります。\n\n味は地域と季節で変わります。寒い北部では薄味でさっぱりと、暑い南部では長く保存できるよう塩気と辛さを強めます。春の葉野菜、夏の若大根、秋の白菜など、旬の材料がそのままキムチになります。\n\n同じレシピでも作る人によって味が変わる「手の味」も大切です。晩秋に家族で大量のキムチを仕込むキムジャン文化は、ユネスコ無形文化遺産にも登録されています。`,
    'zh-TW': `許多人以為泡菜就是紅色的白菜泡菜，其實它的世界更廣。蘿蔔塊泡菜、整根小蘿蔔泡菜、夾餡黃瓜泡菜，以及不放辣椒粉的白泡菜，種類多達數百種。\n\n泡菜的味道會隨地區與季節變化。寒冷北方的口味較清爽，炎熱南方則常做得更鹹更辣，以便長時間保存。春天的嫩菜、夏天的小蘿蔔、秋天的白菜，當季食材都能成為泡菜。\n\n關鍵還在製作者的「手味」。即使配方相同，不同家庭做出的味道也不同。深秋全家一起大量製作泡菜的「김장」文化，也被列入聯合國教科文組織非物質文化遺產。`,
    es: `Muchas personas imaginan que el kimchi es solo col roja y picante, pero existen cientos de variedades: kkakdugi de rábano en dados, chonggak de rábanos jóvenes, pepino relleno y kimchi blanco sin chile.\n\nEl sabor cambia con la región y la estación. En el norte frío suele ser más ligero; en el sur cálido, más salado y picante para conservarse mejor. Las verduras de primavera, el rábano de verano y la col de otoño se convierten en kimchi de temporada.\n\nTambién importa el sonmat, el toque de quien cocina. Cada familia crea un sabor distinto. La tradición comunitaria del gimjang, cuando las familias preparan kimchi en otoño, está reconocida por la UNESCO como patrimonio cultural inmaterial.`,
  },
  'shared-stew': {
    'zh-CN': `韩国餐桌中央常放着一锅仍在沸腾的汤，大家一起分享。对初次体验的人来说可能陌生，但它源于“分享食物就是分享心意”的长期情感。\n\n大酱汤、泡菜汤和嫩豆腐汤都是韩国人的家常慰藉。它们常装在砂锅里端上桌，端来后还会持续冒泡。把汤汁浇在一勺米饭上，就能组成满足的一口。\n\n如今，重视卫生的餐厅通常会提供个人小碗，大家先分到自己的碗里再吃。砂锅温度很高，入口前请稍微放凉，慢慢享用。`,
    ja: `韓国の食卓の中央には、ぐつぐつ煮立つチゲが置かれ、みんなで分けて食べることがあります。初めて見ると戸惑うかもしれませんが、「食べ物を分けることは心を分け合うこと」という感覚が背景にあります。\n\nテンジャンチゲ、キムチチゲ、スンドゥブチゲは韓国のソウルフードです。トゥッペギという土鍋で熱いまま運ばれ、ご飯に汁を少しかけるだけでも満足できる一口になります。\n\n衛生を大切にする現在は、取り分け用の個人皿を用意する店が増えました。土鍋は長く熱いままなので、少し冷ましてからゆっくり味わってください。`,
    'zh-TW': `韓國餐桌中央常放著一鍋仍在沸騰的湯，大家一起分享。對第一次體驗的人而言或許陌生，但它源自「分享食物就是分享心意」的長久情感。\n\n大醬湯、泡菜湯與嫩豆腐湯都是韓國人的家常慰藉。它們常裝在砂鍋裡端上桌，端來後還會持續冒泡。把湯汁澆在一匙白飯上，就能組成滿足的一口。\n\n現在重視衛生的餐廳通常會提供個人小碗，大家先分到自己的碗裡再吃。砂鍋溫度很高，入口前請稍微放涼，慢慢享用。`,
    es: `En el centro de una mesa coreana suele haber una olla de jjigae todavía hirviendo para compartir. Puede resultar extraño la primera vez, pero nace de una idea antigua: compartir la comida también es compartir afecto.\n\nEl doenjang jjigae, el kimchi jjigae y el sundubu jjigae son platos reconfortantes. Llegan en una olla de barro llamada ttukbaegi y siguen burbujeando en la mesa. Un poco de caldo sobre una cucharada de arroz puede formar un bocado completo.\n\nHoy muchos restaurantes ofrecen cuencos individuales para repartir la comida de forma más higiénica. La olla conserva mucho calor, así que deja enfriar cada cucharada antes de probarla.`,
  },
  haejangguk: {
    'zh-CN': `如果前一晚喝多了，韩国人第二天早上常会去喝“해장국”，也就是帮助缓解酒后不适的热汤。一碗热汤配米饭，会让沉重的胃慢慢舒服起来。\n\n醒酒汤种类很多：豆芽醒酒汤、浓郁的猪骨醒酒汤、牛血汤、干明太鱼汤等，可以按地区与口味选择。豆芽汤里还常加入青阳辣椒，做成清爽又辛辣的味道。\n\n在聚餐饮酒文化发达的韩国，第二天“醒酒”几乎成了一种仪式，因此城市里很容易找到24小时营业的醒酒汤店。即使没有喝酒，在饥饿或寒冷的日子里也很适合来一碗。`,
    ja: `前の晩に飲みすぎたとき、韓国では翌朝に「ヘジャングク」を食べる人が多くいます。「ヘジャン」は酒の酔いを解くという意味で、熱いスープとご飯が重い胃をやさしく落ち着かせます。\n\n豆もやし、豚骨、牛の血を固めたソンジ、干しスケトウダラなど種類は豊富です。地域や好みによって選び、豆もやしのスープには青唐辛子を加えて辛くすることもあります。\n\n会食や飲み会の多い韓国では、翌朝のヘジャンが一つの習慣になり、24時間営業の店もよく見かけます。お酒を飲んでいなくても、寒い日や空腹のときにぴったりの温かい料理です。`,
    'zh-TW': `如果前一晚喝多了，韓國人隔天早上常會去喝「해장국」，也就是幫助緩解酒後不適的熱湯。一碗熱湯配白飯，會讓沉重的胃慢慢舒服起來。\n\n醒酒湯種類很多：豆芽醒酒湯、濃郁的豬骨醒酒湯、牛血湯、乾明太魚湯等，可以依地區與口味選擇。豆芽湯裡也常加入青陽辣椒，做成清爽又辛辣的味道。\n\n在聚餐飲酒文化發達的韓國，隔天「醒酒」幾乎成了一種儀式，因此城市裡很容易找到24小時營業的醒酒湯店。即使沒有喝酒，在飢餓或寒冷的日子裡也很適合來一碗。`,
    es: `Después de una noche de excesos, muchos coreanos buscan haejangguk a la mañana siguiente. Haejang significa aliviar los efectos de la bebida, y un cuenco de caldo caliente con arroz ayuda a calmar el estómago.\n\nHay muchas variedades: con brotes de soja, hueso de cerdo, seonji o abadejo seco. Cada región y cada persona tiene su favorita; la versión con brotes puede llevar chile cheongyang para darle más intensidad.\n\nEn Corea, recuperarse con una sopa al día siguiente se ha convertido casi en un ritual, por eso abundan los locales abiertos las 24 horas. Incluso sin haber bebido, es un plato muy reconfortante cuando hace frío o se tiene hambre.`,
  },
  'metal-chopsticks': {
    'zh-CN': `坐上韩国餐桌，最先引人注意的常是金属餐具。与多使用木筷的邻国不同，韩国通常把扁平金属筷和长勺配成一套，合称“수저”。\n\n它们的分工很清楚：米饭和汤用勺，小菜用筷。因为韩国汤类丰富，所以勺子总会一起摆上桌。金属筷比较滑，刚开始可能不容易使用，慢慢练习就好。\n\n餐桌上还有一些小礼仪：通常等年长者先拿起餐具再开始吃饭，饭碗则放在桌上，不端在手里。了解这些细节，会让你在韩国用餐时更自然自在。`,
    ja: `韓国の食卓でまず目に入るのは金属の食器です。木やプラスチックの箸を使う近隣国とは異なり、韓国では平たい金属箸と長いスプーンを一組にし、合わせて「スジョ」と呼びます。\n\n役割もはっきりしています。ご飯と汁物はスプーン、おかずは箸で食べます。汁物の多い韓国料理だからこそ、スプーンがいつも一緒に置かれます。金属箸は少し滑りやすいので、慣れるまでゆっくり試してください。\n\n年長者が先に食器を持ってから食べ始める、ご飯茶碗は持ち上げずテーブルに置く、といった小さなマナーもあります。知っておくと韓国での食事がより自然で楽しくなります。`,
    'zh-TW': `坐上韓國餐桌，最先引人注意的常是金屬餐具。與多使用木筷的鄰國不同，韓國通常把扁平金屬筷與長湯匙配成一套，合稱「수저」。\n\n它們的分工很清楚：白飯和湯用湯匙，小菜用筷子。因為韓國湯類豐富，所以湯匙總會一起擺上桌。金屬筷比較滑，剛開始可能不容易使用，慢慢練習即可。\n\n餐桌上還有一些小禮儀：通常等年長者先拿起餐具再開始吃飯，飯碗則放在桌上，不端在手裡。了解這些細節，會讓你在韓國用餐時更自然自在。`,
    es: `Al sentarte a una mesa coreana llaman la atención los cubiertos metálicos. A diferencia de otros países de la región, Corea combina palillos planos de metal con una cuchara larga; el conjunto se llama sujeo.\n\nSus funciones están bien definidas: la cuchara se usa para el arroz y la sopa, y los palillos para los acompañamientos. Como la cocina coreana incluye muchos caldos, la cuchara siempre está presente. Los palillos metálicos pueden resbalar al principio, así que tómatelo con calma.\n\nTambién hay pequeñas normas: se suele empezar cuando la persona mayor levanta sus cubiertos y el cuenco de arroz permanece sobre la mesa. Conocer estos detalles hace que comer en Corea resulte más natural.`,
  },
};
